# This template is for configuring your docker-compose profile for all microservices.
# You should copy this file to application-dev.yml before changing configuration.

system.name: DOCKER-COMPOSE

# accumulo:
#   zookeepers: 'hostname:port,hostname:port,...'
#   metrics:
#     zookeepers: 'hostname:port,hostname:port,...'

server:
  ssl:
    trust-store: '/etc/pki/testCA.p12'
    trust-store-type: PKCS12
    trust-store-password: 'ChangeIt'
    key-store: '/etc/pki/testServer.p12'
    key-store-type: PKCS12
    key-store-password: 'ChangeIt'

# Define the client certificates (in lower-case subjectDN<issuerDN> form) that are allowed to call a service. Note that you only need to
# specify one value in the list below.
# Since enforce-allowed-callers is false, you can skip configuring this section if you want.
spring:
  security:
    datawave:
      enforce-allowed-callers: false
      allowed-callers:
        - "cn=test a. user, ou=example developers, o=example corp, c=us<cn=example corp ca, o=example corp, c=us>"

# To report metrics to the console, uncomment the following:
#metrics:
#  reporter:
#    factory-class: datawave.metrics.ConsoleMetricsReporterFactory
#    interval: 5
#    time-unit: MINUTES
#metrics:
#  reporter:
#    factory-class: datawave.metrics.TimelyMetricsReporterFactory
#    port: 54321
#    host: localhost
