spring:
  cloud:
    stream:
      bindings:
        queryMetricSource:
          destination: queryMetricChannel
          producer:
            requiredGroups: queryMetricService

datawave.query.metric.client.sink.enabled: false