# This profile should be included by any service which depends on the query starter.  This
# file contains all of the configuration required to use the QueryLogicFactory.
warehouse:
  accumulo:
    zookeepers: '${accumulo.zookeepers}'
    instanceName: '${accumulo.instanceName}'
    username: '${accumulo.username}'
    password: '${accumulo.password}'
  statsd:
    host: localhost
    port: 8125
  tables:
    shard:
      name: 'datawave.shard'
    index:
      name: 'datawave.shardIndex'
    reverseIndex:
      name: 'datawave.shardReverseIndex'
    dateIndex:
      name: 'datawave.dateIndex'
    metadata:
      name: 'datawave.metadata'
    model:
      name: 'datawave.metadata'
  defaults:
    checkpointable: true
    queryThreads: 100
    indexLookupThreads: 100
    dateIndexThreads: 20
    fullTableScanEnabled: false
    baseIteratorPriority: 100
    maxIndexScanTimeMillis: 31536000000
    eventPerDayThreshold: 40000
    shardsPerDayThreshold: 20
    maxTermThreshold: 2000
    maxDepthThreshold: 2000
    maxUnfieldedExpansionThreshold: 50
    maxValueExpansionThreshold: 50
    maxOrExpansionThreshold: 500
    maxOrRangeThreshold: 10
    maxOrExpansionFstThreshold: 750
    maxFieldIndexRangeSplit: 16
    maxIvaratorSources: 20
    maxEvaluationPipelines: 16
    maxPipelineCachedResults: 16
    hdfsSiteConfigURLs: 'file:///etc/hadoop/conf/core-site.xml,file:///etc/hadoop/conf/hdfs-site.xml'
    ivaratorFstHdfsBaseURIs: 'hdfs:///data'
    ivaratorCacheBufferSize: 10000
    ivaratorMaxOpenFiles: 100
    ivaratorCacheScanPersistThreshold: 100000
    ivaratorCacheScanTimeoutMinutes: 60
    modelName: 'DATAWAVE'

datawave:
  metadata:
    all-metadata-auths:
      - PRIVATE,PUBLIC
    type-substitutions:
      "[datawave.data.type.DateType]": "datawave.data.type.RawDateType"

  query:
    parser:
      skipTokenizeUnfieldedFields:
        - "DOMETA"
      tokenizedFields:
        - "CONTENT"
      uuidTypes:
        - fieldName: "EVENT_ID"
          definedView: "LuceneUUIDEventQuery"
          allowedWildcardAfter: 28
        - fieldName: "UUID"
          definedView: "LuceneUUIDEventQuery"
        - fieldName: "PARENT_UUID"
          definedView: "LuceneUUIDEventQuery"
        - fieldName: "PAGE_ID"
          definedView: "LuceneUUIDEventQuery"
        - fieldName: "PAGE_TITLE"
          definedView: "LuceneUUIDEventQuery"
    logic:
      factory:
        enabled: true
        # Uncomment the following line to override the query logic beans to load
        # xmlBeansPath: "classpath:MyTestQueryLogicFactory.xml"

        # The max page size that a user can request.  0 turns off this feature
        maxPageSize: 10000

        # The number of bytes at which a page will be returned, event if the pagesize has not been reached.  0 turns off this feature
        pageByteTrigger: 0
      logics:
        BaseEventQuery:
          checkpointable: ${warehouse.defaults.checkpointable}
          accumuloPassword: ${warehouse.accumulo.password}
          tableName: ${warehouse.tables.shard.name}
          dateIndexTableName: ${warehouse.tables.dateIndex.name}
          defaultDateTypeName: "EVENT"
          metadataTableName: ${warehouse.tables.metadata.name}
          indexTableName: ${warehouse.tables.index.name}
          reverseIndexTableName: ${warehouse.tables.reverseIndex.name}
          maxResults: 369
          queryThreads: ${warehouse.defaults.queryThreads}
          indexLookupThreads: ${warehouse.defaults.indexLookupThreads}
          dateIndexThreads: ${warehouse.defaults.dateIndexThreads}
          fullTableScanEnabled: ${warehouse.defaults.fullTableScanEnabled}
          includeDataTypeAsField: false
          disableIndexOnlyDocuments: false
          indexOnlyFilterFunctionsEnabled: false
          includeHierarchyFields: false
          hierarchyFieldOptions:
            "FOO": "BAR"
          baseIteratorPriority: ${warehouse.defaults.baseIteratorPriority}
          maxIndexScanTimeMillis: ${warehouse.defaults.maxIndexScanTimeMillis}
          collapseUids: false
          collapseUidsThreshold: -1
          useEnrichers: true
          contentFieldNames:
            - 'CONTENT'
          realmSuffixExclusionPatterns:
            - '<.*>$'
          minimumSelectivity: .2
          enricherClassNames:
            - 'datawave.query.enrich.DatawaveTermFrequencyEnricher'
          useFilters: false
          filterClassNames:
            - 'foo.bar'
          filterOptions:
            'bar': "foo"
          auditType: "ACTIVE"
          logicDescription: "Retrieve sharded events/documents, leveraging the global index tables as needed"
          eventPerDayThreshold: ${warehouse.defaults.eventPerDayThreshold}
          shardsPerDayThreshold: ${warehouse.defaults.shardsPerDayThreshold}
          maxTermThreshold: ${warehouse.defaults.maxTermThreshold}
          maxDepthThreshold: ${warehouse.defaults.maxDepthThreshold}
          maxUnfieldedExpansionThreshold: ${warehouse.defaults.maxUnfieldedExpansionThreshold}
          maxValueExpansionThreshold: ${warehouse.defaults.maxValueExpansionThreshold}
          maxOrExpansionThreshold: ${warehouse.defaults.maxOrExpansionThreshold}
          maxOrRangeThreshold: ${warehouse.defaults.maxOrRangeThreshold}
          maxOrExpansionFstThreshold: ${warehouse.defaults.maxOrExpansionFstThreshold}
          maxFieldIndexRangeSplit: ${warehouse.defaults.maxFieldIndexRangeSplit}
          maxIvaratorSources: ${warehouse.defaults.maxIvaratorSources}
          maxEvaluationPipelines: ${warehouse.defaults.maxEvaluationPipelines}
          maxPipelineCachedResults: ${warehouse.defaults.maxPipelineCachedResults}
          hdfsSiteConfigURLs: ${warehouse.defaults.hdfsSiteConfigURLs}
          zookeeperConfig: ${warehouse.accumulo.zookeepers}
          ivaratorCacheDirConfigs:
            - basePathURI: "hdfs:///data"
          ivaratorFstHdfsBaseURIs: ${warehouse.defaults.ivaratorFstHdfsBaseURIs}
          ivaratorCacheBufferSize: ${warehouse.defaults.ivaratorCacheBufferSize}
          ivaratorMaxOpenFiles: ${warehouse.defaults.ivaratorMaxOpenFiles}
          ivaratorCacheScanPersistThreshold: ${warehouse.defaults.ivaratorCacheScanPersistThreshold}
          ivaratorCacheScanTimeoutMinutes: ${warehouse.defaults.ivaratorCacheScanTimeoutMinutes}
          eventQueryDataDecoratorTransformer:
            requestedDecorators:
              - "CSV"
              - "WIKIPEDIA"
            dataDecorators:
              "CSV":
                "EVENT_ID": "https://localhost:8443/DataWave/Query/lookupUUID/EVENT_ID?uuid=@field_value@&amp;parameters=data.decorators:CSV"
                "UUID": "https://localhost:8443/DataWave/Query/lookupUUID/UUID?uuid=@field_value@&amp;parameters=data.decorators:CSV"
                "PARENT_UUID": "https://localhost:8443/DataWave/Query/lookupUUID/PARENT_UUID?uuid=@field_value@&amp;parameters=data.decorators:CSV"
              "WIKIPEDIA":
                "PAGE_ID": "https://localhost:8443/DataWave/Query/lookupUUID/PAGE_ID?uuid=@field_value@&amp;parameters=data.decorators:WIKIPEDIA"
                "PAGE_TITLE": "https://localhost:8443/DataWave/Query/lookupUUID/PAGE_TITLE?uuid=@field_value@&amp;parameters=data.decorators:WIKIPEDIA"
          modelTableName: ${warehouse.tables.model.name}
          modelName: ${warehouse.defaults.modelName}
          querySyntaxParsers:
            JEXL: ""
            LUCENE: "LuceneToJexlQueryParser"
            LUCENE-UUID: "LuceneToJexlUUIDQueryParser"
            TOKENIZED-LUCENE: "TokenizedLuceneToJexlQueryParser"
          sendTimingToStatsd: false
          collectQueryMetrics: true
          logTimingDetails: true
          statsdHost: ${warehouse.statsd.host}
          statsdPort: ${warehouse.statsd.port}
          evaluationOnlyFields: ""
          maxConcurrentTasks: 10
          requiredRoles:
            - "AuthorizedUser"
