# This profile should be added to your service if you depend on the 
# query metric starter to send metrics to the query metric service.
spring:
  cloud:
    stream:
      bindings:
        queryMetricSource-out-0:
          destination: queryMetricChannel
          producer:
            requiredGroups: queryMetricService
    # NOTE: When defining your functions, be sure to include busConsumer, or else spring cloud bus will not work
    function:
      definition: queryMetricSource;busConsumer