# This is where you set properties which are common to all executors
logging:
  level:
    root: INFO
    datawave.query: DEBUG
    datawave.microservice.query: DEBUG
    datawave.microservice.query.executor: DEBUG
    org.apache.kafka: ERROR
    datawave.microservice.query.storage: WARN

warehouse:
  accumulo:
    zookeepers: '${accumulo.zookeepers}'
    instanceName: '${accumulo.instanceName}'
    username: '${accumulo.username}'
    password: '${accumulo.password}'

datawave:
  table:
    cache:
      zookeepers: '${accumulo.zookeepers}'
      tableNames:
        - '${warehouse.tables.metadata.name}'
      poolName: 'default'
      reloadInterval: 360000
      evictionReaperIntervalInSeconds: 360
      numLocks: 3
      maxRetries: 3
  connection:
    factory:
      defaultPool: "default"
      pools:
        "default":
          zookeepers: '${accumulo.zookeepers}'
          instance: '${accumulo.instanceName}'
          username: '${accumulo.username}'
          password: '${accumulo.password}'
          lowPriorityPoolSize: 10
          normalPriorityPoolSize: 10
          highPriorityPoolSize: 10
          adminPriorityPoolSize: 10
  query:
    executor:
      pool: "${executor.poolName}"
      availableResultsPageMultiplier: 2.5
      maxQueueSize: 400
      coreThreads: 10
      maxThreads: 40
      keepAliveMs: 600000
      queryStatusExpirationMs: 60000
      checkpointFlushMs: 1000
      checkpointFlushResults: 2
      monitorTaskLease: 30
      monitorTaskLeaseTimeUnit: SECONDS
      monitor:
        enabled: true
        scheduler-crontab: '* * * * * ?'

