spring:
  lifecycle:
    # Set the shutdown grace period
    timeout-per-shutdown-phase: 5s

management:
  endpoint:
    # Enable the shutdown endpoint for the query service
    shutdown:
      enabled: true

# Query requires a client certificate
server:
  ssl:
    client-auth: NEED
  # Enable graceful shutdown
  shutdown: "graceful"

logging:
  level:
    root: INFO
    org.springframework.cloud.bootstrap.config: DEBUG
    datawave.microservice.query: DEBUG
    org.apache.kafka: ERROR
    datawave.microservice.query.storage: WARN

datawave:
  query:
    nextCall:
      resultPollInterval: 500
      statusUpdateInterval: 500
    expiration:
      callTimeout: 300
      callTimeUnit: SECONDS

audit-client:
  discovery:
    enabled: false
  uri: '${AUDIT_SERVER_URL:http://localhost:11111/audit}'
