# This profile should be added to your service if you depend on the 
# query metric starter to send metrics to the query metric service.
spring:
  cloud:
    stream:
      bindings:
        queryMetricSource-out-0:
          destination: queryMetricChannel
          producer:
            requiredGroups: queryMetricService
            errorChannelEnabled: true
    # NOTE: When defining your functions, be sure to include busConsumer, or else spring cloud bus will not work
    function:
      definition: queryMetricSource;busConsumer

# To send metrics via REST, uncomment the following
#datawave:
#  query:
#    metric:
#      client:
#        host: metrics
#        transport: HTTPS
