
# This data file describes all-config.xml config settings

properties:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

