
# This data file describes settings in ingest-config.xml

properties:
  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

