version: "2.2"

services:
  rabbitmq:
    image: rabbitmq:3.7.7-alpine
    volumes:
      - ${RABBITMQ_CONFIG_DIR:-./rabbitmq-config}:/etc/rabbitmq
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_ERLANG_COOKIE="mycookie"
    network_mode: host

  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    network_mode: host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_started

  kafdrop:
    image: obsidiandynamics/kafdrop
    network_mode: host
    environment:
      - KAFKA_BROKERCONNECT=localhost:9092
    depends_on:
      kafka:
        condition: service_started
