# Base Event Query configs, from QLF.xml

properties:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

